name: CI (Lint, TypeCheck, E2E Tests)

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Install Node v18
        with:
          node-version: 18

      - run: |
          sh ./bin/bootstrap.sh
          sh ./bin/type-check.sh
        name: Install dependencies & Run CI checks

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests for RoadToJobs
        run: cd tests-e2e && npx playwright test


