name: CI (Lint, TypeCheck, E2E Tests)

env:
  ROOT_DIR: "/home/runner/work/roadtojobs/roadtojobs"

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Install Node v18
        with:
          node-version: 18

      - name: Install dependencies & Run CI checks
        run: |
          sh ./bin/bootstrap.sh
          sh ./bin/type-check.sh

      - name: Install & Start SurrealDB
        run: |
          curl -sSf https://install.surrealdb.com | sh
          surreal start --log trace --user root --pass root memory &

      - name: Run migrations & seeders
        run: |
          cd $ROOT_DIR/server
          npm run dev:fresh

      - name: Run web-app
        run: |
          cd $ROOT_DIR/web
          npm run build
          npm run preview &
          sleep 5
          curl http://localhost:3000

      - name: Install Playwright Chromium
        run: |
          cd $ROOT_DIR/tests-e2e
          npx playwright install --with-deps chromium


      - name: Run E2E tests for RoadToJobs
        run: |
          cd $ROOT_DIR/tests-e2e
          npm run start:ci

      - uses: actions/upload-artifact@v3
        name: Store artifacts
        if: always()
        with:
          name: playwright-report
          path: ${{ env.ROOT_DIR }}/tests-e2e/playwright-report/
          retention-days: 3


